language: ruby
bundler_args: --local --without=development --deployment --jobs=3 --retry=3
cache: bundler
addons:
  postgresql: "9.3"
rvm:
  - 2.2.3
before_install:
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start 9.3
  - redis-server &
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - curl -L -o bundle_cached.tgz https://www.dropbox.com/s/v7x37b2dbydorpd/bundle_cached.tgz?dl=1
  - tar -xf bundle_cached.tgz
  - ls vendor/cache
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - cp config/database.yml.example config/database.yml
  - cp config/github.yml.example config/github.yml
  - cp config/secrets.yml.example config/secrets.yml
  - bundle exec rake db:test:prepare
script:
  - bundle exec rspec spec
  - bundle exec cucumber features
